settings:
  title: 'Status'
  url: 'https://status.itstriple.net' # used for Slack messages
  logo: 'https://cdn.tomas.systems/triple_staff.png' # image in ./public/ folder
  daysInHistogram: 20 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: website
    name: Website
    url: 'https://itstriple.net'
    method: GET
    expectStatus: 200

  - id: api
    name: API
    url: 'https://api.itstriple.net'
    method: GET
    expectStatus: 200
    
  - id: mail
    name: Mail
    url: 'https://webmail.tomas.systems'
    method: GET
    expectStatus: 200


  - id: radio-stream
    name: Stream
    url: 'https://stream.itstriple.net'
    method: GET
    expectStatus: 200
