settings:
  title: 'Aqua | Status Page'
  url: 'https://status.itsaqua.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: aqua-website # unique identifier
    name: Official Website
    description: 'Official Aqua Website' # default=empty
    url: 'https://itsaqua.net' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: staff-panel
    name: Staff Panel
    description: 'Official Aqua Staff Panel'
    url: 'https://staff.itsaqua.net'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: aqua-hub
    name: Aqua Hub
    description: 'Official Aqua Hub for user applications.'
    url: 'https://hub.itsaqua.net'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: aqua-api
    name: API
    description: 'Stats API'
    url: 'https://api.itsaqua.net/stats'
    method: GET
    expectStatus: 200

  - id: aqua-cdn
    name: CDN
    description: 'Image CDN'
    url: 'https://cdn.itsaqua.net'
    method: GET
    expectStatus: 200

  - id: aqua-stream
    name: Radio Stream
    description: 'Live Audio Stream'
    url: 'https://live.itsaqua.net'
    method: GET
    expectStatus: 200

  - id: aqua-verification
    name: Verification
    description: 'Discord Verification System'
    url: 'https://verify.itsaqua.net/checkalive'
    method: GET
    expectStatus: 200
    
  - id: aqua-bot
    name: Discord Bot
    description: 'Discord Bot'
    url: 'http://de.2.ddidev.xyz:4579'
    method: GET
    expectStatus: 200

  - id: aqua-lnk
    name: Link Shortener Service
    description: 'Link Shortener Service'
    url: 'https://lnk.itsaqua.net'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: aqua-retro
    name: Retro Player
    description: 'Embeddable Retro Player'
    url: 'https://retro.itsaqua.net'
    method: GET
    expectStatus: 200

  - id: aqua-migadu
    name: Migadu
    description: 'Mail Provider'
    url: 'https://www.migadu.com'
    method: GET
    expectStatus: 200
